/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CustomStudioRouteImport } from './routes/custom-studio'
import { Route as CustomOrderRouteImport } from './routes/custom-order'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WebhooksPaystackRouteImport } from './routes/webhooks/paystack'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as OrderConfirmationReferenceRouteImport } from './routes/order-confirmation.$reference'
import { Route as ApiLaundryOrderRouteImport } from './routes/api/laundry-order'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomStudioRoute = CustomStudioRouteImport.update({
  id: '/custom-studio',
  path: '/custom-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrderRoute = CustomOrderRouteImport.update({
  id: '/custom-order',
  path: '/custom-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WebhooksPaystackRoute = WebhooksPaystackRouteImport.update({
  id: '/webhooks/paystack',
  path: '/webhooks/paystack',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const OrderConfirmationReferenceRoute =
  OrderConfirmationReferenceRouteImport.update({
    id: '/order-confirmation/$reference',
    path: '/order-confirmation/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLaundryOrderRoute = ApiLaundryOrderRouteImport.update({
  id: '/api/laundry-order',
  path: '/api/laundry-order',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/custom-studio': typeof CustomStudioRoute
  '/delivery': typeof DeliveryRoute
  '/faqs': typeof FaqsRoute
  '/lookbook': typeof LookbookRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/laundry-order': typeof ApiLaundryOrderRoute
  '/order-confirmation/$reference': typeof OrderConfirmationReferenceRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/webhooks/paystack': typeof WebhooksPaystackRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/custom-studio': typeof CustomStudioRoute
  '/delivery': typeof DeliveryRoute
  '/faqs': typeof FaqsRoute
  '/lookbook': typeof LookbookRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/laundry-order': typeof ApiLaundryOrderRoute
  '/order-confirmation/$reference': typeof OrderConfirmationReferenceRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/webhooks/paystack': typeof WebhooksPaystackRoute
  '/admin': typeof AdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/custom-order': typeof CustomOrderRoute
  '/custom-studio': typeof CustomStudioRoute
  '/delivery': typeof DeliveryRoute
  '/faqs': typeof FaqsRoute
  '/lookbook': typeof LookbookRoute
  '/payment': typeof PaymentRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shop': typeof ShopRouteWithChildren
  '/size-guide': typeof SizeGuideRoute
  '/terms': typeof TermsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/laundry-order': typeof ApiLaundryOrderRoute
  '/order-confirmation/$reference': typeof OrderConfirmationReferenceRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/webhooks/paystack': typeof WebhooksPaystackRoute
  '/admin/': typeof AdminIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/custom-order'
    | '/custom-studio'
    | '/delivery'
    | '/faqs'
    | '/lookbook'
    | '/payment'
    | '/privacy'
    | '/returns'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/laundry-order'
    | '/order-confirmation/$reference'
    | '/shop/$slug'
    | '/webhooks/paystack'
    | '/admin/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/custom-order'
    | '/custom-studio'
    | '/delivery'
    | '/faqs'
    | '/lookbook'
    | '/payment'
    | '/privacy'
    | '/returns'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/laundry-order'
    | '/order-confirmation/$reference'
    | '/shop/$slug'
    | '/webhooks/paystack'
    | '/admin'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collection'
    | '/contact'
    | '/custom-order'
    | '/custom-studio'
    | '/delivery'
    | '/faqs'
    | '/lookbook'
    | '/payment'
    | '/privacy'
    | '/returns'
    | '/shop'
    | '/size-guide'
    | '/terms'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/api/laundry-order'
    | '/order-confirmation/$reference'
    | '/shop/$slug'
    | '/webhooks/paystack'
    | '/admin/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  CustomOrderRoute: typeof CustomOrderRoute
  CustomStudioRoute: typeof CustomStudioRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqsRoute: typeof FaqsRoute
  LookbookRoute: typeof LookbookRoute
  PaymentRoute: typeof PaymentRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SizeGuideRoute: typeof SizeGuideRoute
  TermsRoute: typeof TermsRoute
  ApiLaundryOrderRoute: typeof ApiLaundryOrderRoute
  OrderConfirmationReferenceRoute: typeof OrderConfirmationReferenceRoute
  WebhooksPaystackRoute: typeof WebhooksPaystackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-studio': {
      id: '/custom-studio'
      path: '/custom-studio'
      fullPath: '/custom-studio'
      preLoaderRoute: typeof CustomStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-order': {
      id: '/custom-order'
      path: '/custom-order'
      fullPath: '/custom-order'
      preLoaderRoute: typeof CustomOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/webhooks/paystack': {
      id: '/webhooks/paystack'
      path: '/webhooks/paystack'
      fullPath: '/webhooks/paystack'
      preLoaderRoute: typeof WebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/order-confirmation/$reference': {
      id: '/order-confirmation/$reference'
      path: '/order-confirmation/$reference'
      fullPath: '/order-confirmation/$reference'
      preLoaderRoute: typeof OrderConfirmationReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/laundry-order': {
      id: '/api/laundry-order'
      path: '/api/laundry-order'
      fullPath: '/api/laundry-order'
      preLoaderRoute: typeof ApiLaundryOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  CustomOrderRoute: CustomOrderRoute,
  CustomStudioRoute: CustomStudioRoute,
  DeliveryRoute: DeliveryRoute,
  FaqsRoute: FaqsRoute,
  LookbookRoute: LookbookRoute,
  PaymentRoute: PaymentRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShopRoute: ShopRouteWithChildren,
  SizeGuideRoute: SizeGuideRoute,
  TermsRoute: TermsRoute,
  ApiLaundryOrderRoute: ApiLaundryOrderRoute,
  OrderConfirmationReferenceRoute: OrderConfirmationReferenceRoute,
  WebhooksPaystackRoute: WebhooksPaystackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
